# Generated by Django 5.2.1 on 2025-06-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="coef",
            field=models.CharField(max_length=10),
        ),
    ]
